/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Adminstrador;

import Design.*;

/**
 *
 * @author sofia
 */
public class AdicionarProduto extends javax.swing.JFrame {

    DesignAdicionarProdutos design = new DesignAdicionarProdutos();
    
    public AdicionarProduto() {
        initComponents();
        
        design.titulo(titulo, this);
        design.BotaoCancelar(botaoCancelar, this);
        design.BotaoProximo(BotaoProximo, this);
        design.textoLabel(nomeProduto, descricaoProduto, personalizacaoProduto, tempoProduto, minsProduto, precoProduto, this);
        design.textField(escreverNome, escreverDescricao, this);
        design.spinner(spinnerTempo, spinnerPreco, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        nomeProduto = new javax.swing.JLabel();
        tempoProduto = new javax.swing.JLabel();
        precoProduto = new javax.swing.JLabel();
        descricaoProduto = new javax.swing.JLabel();
        personalizacaoProduto = new javax.swing.JLabel();
        escreverDescricao = new javax.swing.JTextField();
        escreverNome = new javax.swing.JTextField();
        spinnerTempo = new javax.swing.JSpinner();
        minsProduto = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        botaoCancelar = new javax.swing.JButton();
        BotaoProximo = new javax.swing.JButton();
        spinnerPreco = new javax.swing.JSpinner();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("AdicionarProduto"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 550));

        titulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        titulo.setText("Adicionar Produto");

        nomeProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nomeProduto.setText("Nome:");

        tempoProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tempoProduto.setText("Tempo:");

        precoProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        precoProduto.setText("Preço:");

        descricaoProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        descricaoProduto.setText("Descrição:");

        personalizacaoProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        personalizacaoProduto.setText("Personalização:");

        escreverDescricao.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        escreverDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        escreverDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        escreverDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escreverDescricaoActionPerformed(evt);
            }
        });

        escreverNome.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        spinnerTempo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        spinnerTempo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 90, 1));

        minsProduto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        minsProduto.setText("mins");

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botaoCancelar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoCancelar.setText("Cancelar");

        BotaoProximo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoProximo.setText("Próximo");
        BotaoProximo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        spinnerPreco.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        spinnerPreco.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, null, 0.1d));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personalizacaoProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(precoProduto)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titulo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(descricaoProduto)))
                                        .addGap(117, 117, 117))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(escreverNome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(spinnerPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(48, 48, 48)
                                        .addComponent(escreverDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jComboBox1, 0, 136, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tempoProduto)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minsProduto)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoProximo)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titulo)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeProduto)
                            .addComponent(escreverNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempoProduto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spinnerTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(minsProduto)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoProduto)
                            .addComponent(spinnerPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(BotaoProximo))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoProduto)
                    .addComponent(personalizacaoProduto))
                .addGap(18, 18, 18)
                .addComponent(escreverDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escreverDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escreverDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escreverDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoProximo;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JLabel descricaoProduto;
    private javax.swing.JTextField escreverDescricao;
    private javax.swing.JTextField escreverNome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel minsProduto;
    private javax.swing.JLabel nomeProduto;
    private javax.swing.JLabel personalizacaoProduto;
    private javax.swing.JLabel precoProduto;
    private javax.swing.JSpinner spinnerPreco;
    private javax.swing.JSpinner spinnerTempo;
    private javax.swing.JLabel tempoProduto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
