package Adminstrador;

import Design.*;
import BD.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * Adiciona ou remove as categorias dos produtos
 *
 * @author sofia
 */
public class AdicionarCategoria extends javax.swing.JFrame {

    DesignAdicionarCategoria design = new DesignAdicionarCategoria(this);
    Produtos produto = new Produtos();

    short selecao;

    public AdicionarCategoria() throws ClassNotFoundException, SQLException {
        initComponents();

        //design dos componentes
        design.titulo(titulo);
        design.botao(adicionarCategoria, removerCategoria, cancelar);
        design.lista(listaCategorias);
        design.escrever(escreverCategoria);
        design.textoErro(erro);

        //busca as categorias da base de dados e coloca na lista para o utilizador ver
        categoriasLista();

        //tornar invisivel
        escreverCategoria.setVisible(false);
        erro.setVisible(false);
    }

    /**
     * Adiciona todas as categorias que estam na base de dados na lista
     */
    public void categoriasLista() throws ClassNotFoundException, SQLException {

        DefaultListModel dlm = new DefaultListModel();

        String[] categorias = produto.verDados("Categoria").split("\n");
        
        for (String n : categorias) {
            dlm.addElement(n);
        }

        listaCategorias.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCategorias = new javax.swing.JList<>();
        adicionarCategoria = new javax.swing.JButton();
        removerCategoria = new javax.swing.JButton();
        escreverCategoria = new javax.swing.JTextField();
        erro = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("categoria"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 350));

        titulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        titulo.setText("Categorias");

        listaCategorias.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listaCategorias);

        adicionarCategoria.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        adicionarCategoria.setText("Adicionar");
        adicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCategoriaActionPerformed(evt);
            }
        });

        removerCategoria.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        removerCategoria.setText("Remove");
        removerCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCategoriaActionPerformed(evt);
            }
        });

        escreverCategoria.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        escreverCategoria.setText("ex: Lanche");

        erro.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        erro.setText("jLabel1");

        cancelar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escreverCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarCategoria)
                    .addComponent(erro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerCategoria)
                    .addComponent(cancelar)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(escreverCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(erro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Adiciona categorias à base de dados que o utilizador escolher
     *
     * @param evt
     */
    private void adicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCategoriaActionPerformed
        escreverCategoria.setVisible(true);

        adicionarCategoria.setText("OK");

        selecao += 1;
        if (selecao == 2 && escreverCategoria.getText().equals("ex: Lanche")) {
            erro.setVisible(true);
            erro.setText("Nada foi alterado.");
            selecao = 1;
        } else {
            try {
                if (selecao == 2 && produto.dadoProduto("Categoria", escreverCategoria.getText())) {
                    produto.adicionarDados("Categoria", escreverCategoria.getText());
                    categoriasLista();
                    selecao = 0;
                    erro.setVisible(false);
                    adicionarCategoria.setText("Adicionar");
                    escreverCategoria.setVisible(false);
                } else if (selecao == 2) {
                    selecao = 1;
                    erro.setVisible(true);
                    erro.setText("A categoria já existe.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AdicionarCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_adicionarCategoriaActionPerformed

    private void removerCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCategoriaActionPerformed

        try {
            produto.removerDado("Categoria", listaCategorias.getSelectedValue());
            categoriasLista();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdicionarCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_removerCategoriaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
        
        
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdicionarCategoria().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(AdicionarCategoria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCategoria;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel erro;
    private javax.swing.JTextField escreverCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCategorias;
    private javax.swing.JButton removerCategoria;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
