package Adminstrador;

import Thread.*;
import BD.Identidade;
import Design.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Configuração para mudar o nome de utilizador e palavra-passe padrão
 *
 * @author sofia
 */
public class ConfigurarConta extends javax.swing.JFrame {

    private DesignConfigurarConta design = new DesignConfigurarConta(this);
    private Identidade c = new Identidade();

    public ConfigurarConta() {
        initComponents();

        erroPasse.setVisible(false);

        //design dos componentes
        design.titulo(tituloConfigurarConta);
        design.BotaoProximo(BotaoProximo);
        design.BotaoCancelar(botaoCancelar);

        design.label(textoNomeUtilizador, textoNovaPasse, textoRepetirPasse);
        design.textField(escreverNomeUtilizador, escreverNovaPasse, repetirPasse);
        design.textoErro(erroPasse);

        design.progressBar(progressBar);

        //barra de progresso
        progressBar.setStringPainted(true);
        progressBar.setValue(0);
        progressBar.setString(0 + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloConfigurarConta = new javax.swing.JLabel();
        textoRepetirPasse = new javax.swing.JLabel();
        textoNomeUtilizador = new javax.swing.JLabel();
        escreverNomeUtilizador = new javax.swing.JTextField();
        textoNovaPasse = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        BotaoProximo = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        escreverNovaPasse = new javax.swing.JPasswordField();
        repetirPasse = new javax.swing.JPasswordField();
        erroPasse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ConfigurarConta"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 550));

        tituloConfigurarConta.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        tituloConfigurarConta.setText("Configuração da conta");

        textoRepetirPasse.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoRepetirPasse.setText("Repita a palavra-passe");

        textoNomeUtilizador.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoNomeUtilizador.setText("Novo nome de utilizador");

        escreverNomeUtilizador.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        escreverNomeUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escreverNomeUtilizadorActionPerformed(evt);
            }
        });

        textoNovaPasse.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoNovaPasse.setText("Nova palavra-passe");

        botaoCancelar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoCancelar.setText("Cancelar");

        BotaoProximo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoProximo.setText("Próximo");
        BotaoProximo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BotaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProximoActionPerformed(evt);
            }
        });

        repetirPasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repetirPasseActionPerformed(evt);
            }
        });

        erroPasse.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloConfigurarConta)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botaoCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(erroPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(BotaoProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoNomeUtilizador)
                    .addComponent(textoNovaPasse)
                    .addComponent(escreverNomeUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(textoRepetirPasse)
                    .addComponent(escreverNovaPasse)
                    .addComponent(repetirPasse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloConfigurarConta)
                .addGap(38, 38, 38)
                .addComponent(textoNomeUtilizador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escreverNomeUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoNovaPasse)
                .addGap(22, 22, 22)
                .addComponent(escreverNovaPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoRepetirPasse)
                .addGap(18, 18, 18)
                .addComponent(repetirPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoCancelar)
                        .addComponent(BotaoProximo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(erroPasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escreverNomeUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escreverNomeUtilizadorActionPerformed

    }//GEN-LAST:event_escreverNomeUtilizadorActionPerformed

    private void BotaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProximoActionPerformed
  
        try {
            if ("".equals(escreverNomeUtilizador.getText())) {
                erroPasse.setVisible(true);
                erroPasse.setText("Tem de inserir um nome de utilizador");
            } else if ("".equals(escreverNovaPasse.getText())) {
                erroPasse.setVisible(true);
                erroPasse.setText("Tem de inserir uma palavra-passe");
            } else if ("".equals(repetirPasse.getText())) {
                erroPasse.setVisible(true);
                erroPasse.setText("Tem de repetir a palavra-passe");
            } else {
                if (escreverNovaPasse.getText().equals(repetirPasse.getText()) && c.verNomeUtilizadorRepetido(escreverNomeUtilizador.getText())) {
                    erroPasse.setVisible(false);
                    Identidade i = new Identidade();
                    i.mudarNomePasse(escreverNomeUtilizador.getText(), escreverNovaPasse.getText());

                    ProgressBar m = new ProgressBar(progressBar);
                    MostrarInterface mi = new MostrarInterface(this, new ConfiguracaoInicial());
                    m.start();
                    mi.start();

                } else if (!c.verNomeUtilizadorRepetido(escreverNomeUtilizador.getText())) {
                    erroPasse.setVisible(true);
                    erroPasse.setText("Esse nome já existe.");
                } else if (!escreverNovaPasse.getText().equals(repetirPasse.getText())) {
                    erroPasse.setVisible(true);
                    erroPasse.setText("As palavras-passes não correspondem.");

                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ConfigurarConta.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BotaoProximoActionPerformed

    private void repetirPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repetirPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repetirPasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigurarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoProximo;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JLabel erroPasse;
    private javax.swing.JTextField escreverNomeUtilizador;
    private javax.swing.JPasswordField escreverNovaPasse;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPasswordField repetirPasse;
    private javax.swing.JLabel textoNomeUtilizador;
    private javax.swing.JLabel textoNovaPasse;
    private javax.swing.JLabel textoRepetirPasse;
    private javax.swing.JLabel tituloConfigurarConta;
    // End of variables declaration//GEN-END:variables

}
