/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Adminstrador;

import BD.*;
import Design.*;
import Thread.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * O admin pode ver a equipa toda
 *
 * @author sofia
 */
public class Equipa extends javax.swing.JFrame {

    private final Identidade identidade;
    private final DesignEquipa design;
    private final VerDados dados;
    private MostrarInterface mostrarInterface;

    private String funcao;
    private int selecionado;
    private boolean menu;

    /**
     * Creates new form Equipa
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public Equipa() throws ClassNotFoundException, SQLException {
        initComponents();

        this.identidade = new Identidade();
        this.selecionado = 0;
        this.design = new DesignEquipa(this);
        this.funcao = null;
        this.dados = new VerDados();

        listas();
        design.titulo(titulo);
        design.progressBar(progressbar);
        design.BotaoAnterior(BotaoAnterior);
        design.BotaoProximo(BotaoProximo);
        design.BotaoCancelar(botaoCancelar);
        design.JButton(botaoAdicionar, botaoAlterar, botaoRemover);
        design.menuTab(jTabbedPane1);

    }

    /**
     * Descricao: coloca nas listas da tabs todos os funcionarios
     * correspondentes
     *
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    public void listas() throws ClassNotFoundException, SQLException {

        DefaultListModel dlm = new DefaultListModel();

        if (selecionado == 3) {
            String[] funcionariosNaoAtivos = identidade.verFuncionarioNaoAtivo().split("\n");
            for (String n : funcionariosNaoAtivos) {
                dlm.addElement(n);
            }
            listaNaoAtivo.setModel(dlm);

        } else {

            switch (selecionado) {
                case 0:
                    funcao = "Admin";
                    break;
                case 1:
                    funcao = "Mesa";
                    break;
                case 2:
                    funcao = "Cozinha";
                    break;
            }

            String[] funcionariosAtivos = identidade.verFuncionarioAtivo(funcao).split("\n");

            for (String n : funcionariosAtivos) {
                dlm.addElement(n);
            }

            switch (selecionado) {
                case 0:
                    listaAdmin.setModel(dlm);
                    break;
                case 1:
                    listaMesa.setModel(dlm);
                    break;
                case 2:
                    listaCozinha.setModel(dlm);
                    break;

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        BotaoProximo = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        BotaoAnterior = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAdmin = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMesa = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCozinha = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaNaoAtivo = new javax.swing.JList<>();
        progressbar = new javax.swing.JProgressBar();
        botaoAdicionar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        titulo.setText("A sua equipa");

        BotaoProximo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoProximo.setText("Menu");
        BotaoProximo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BotaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProximoActionPerformed(evt);
            }
        });

        botaoCancelar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoCancelar.setText("Cancelar");

        BotaoAnterior.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoAnterior.setText("Anterior");
        BotaoAnterior.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(listaAdmin);

        jTabbedPane1.addTab("Administrador ", jScrollPane1);

        jScrollPane2.setViewportView(listaMesa);

        jTabbedPane1.addTab("Empregado de Mesa", jScrollPane2);

        jScrollPane3.setViewportView(listaCozinha);

        jTabbedPane1.addTab("Empregado de Cozinha", jScrollPane3);

        jScrollPane4.setViewportView(listaNaoAtivo);

        jTabbedPane1.addTab("Não ativo", jScrollPane4);

        botaoAdicionar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoAlterar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoRemover.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotaoProximo)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(botaoCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAnterior)
                        .addGap(84, 84, 84)
                        .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botaoRemover))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(botaoAdicionar)
                        .addGap(27, 27, 27)
                        .addComponent(botaoAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRemover)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoProximo)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoCancelar)
                            .addComponent(BotaoAnterior))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Descricao: Adiciona um novo funcionario
     *
     * @param evt
     */
    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        CadastrarEquipa equipa = new CadastrarEquipa();
        ProgressBar pb = new ProgressBar(progressbar);

        if (menu) {
            equipa.interfaceMenu();
        }
        mostrarInterface = new MostrarInterface(this, equipa);
        mostrarInterface.start();
        pb.start();


    }//GEN-LAST:event_botaoAdicionarActionPerformed

    /**
     * Remove um funcionario
     *
     * @param evt
     */
    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed

        try {
            switch (selecionado) {
                case 0:
                    identidade.removerFuncionario(listaAdmin.getSelectedValue(), funcao);
                    break;
                case 1:
                    identidade.removerFuncionario(listaMesa.getSelectedValue(), funcao);
                    break;
                case 2:
                    identidade.removerFuncionario(listaCozinha.getSelectedValue(), funcao);
                    break;
            }
            listas();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Equipa.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoRemoverActionPerformed

    /**
     * Descricao: apresenta uma nova interface com os dados que quer alterar e
     * modifica na base de dados
     *
     * @param evt
     */
    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed

        String nome = null;
        CadastrarEquipa equipa = new CadastrarEquipa();

        try {
            if (selecionado == 3) {
                botaoAlterar.setText("Ativar");
                identidade.ativarFuncionario(listaNaoAtivo.getSelectedValue());
                listas();
            } else {

                switch (selecionado) {
                    case 0:
                        funcao = "Administrador";
                        nome = listaAdmin.getSelectedValue();
                        break;
                    case 1:
                        funcao = "Empregado de cozinha";
                        nome = listaMesa.getSelectedValue();
                        break;
                    case 2:
                        funcao = "Empregado de mesa";
                        nome = listaCozinha.getSelectedValue();
                        break;
                }

                String dados[] = identidade.dadosCadaFuncionario(nome).split("\n");
                equipa.setComboboxTipoFuncionario(funcao);
                equipa.setNomeFuncionario(dados[2]); // insere o nome do funcionario
                equipa.setUsernameFuncionario(dados[0]); //insere o nome de utilizador
                equipa.setPassword(dados[1]); // insere a password
                equipa.setRepetirPassword(dados[1]);
                equipa.setUpdate(true);
                equipa.setID(this.dados.verID("Funcionario", nome));

                if (menu) {
                    equipa.interfaceMenu();
                }
                mostrarInterface = new MostrarInterface(this, equipa);
                mostrarInterface.start();
                ProgressBar pb = new ProgressBar(progressbar);
                pb.start();

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Equipa.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botaoAlterarActionPerformed

    /**
     * Mostra o menu
     *
     * @param evt
     */
    private void BotaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProximoActionPerformed
        mostrarInterface = new MostrarInterface(this, new MenuInicial());
        mostrarInterface.start();
        ProgressBar pb = new ProgressBar(progressbar);
        pb.start();
    }//GEN-LAST:event_BotaoProximoActionPerformed

    /**
     * Quando as tabs são clicadas obtem-se o index da tab e atualiza-se a lista
     * correspondente
     *
     * @param evt
     */
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        selecionado = jTabbedPane1.getSelectedIndex();

        if (selecionado == 3) {
            botaoAlterar.setText("Ativar");
        }

        try {
            listas();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Equipa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * Desativa o botão anterior porque não há uma sequência de interfaces no
     * menu Coloca a variável menu = true
     */
    public void interfaceMenu() {
        BotaoAnterior.setVisible(false);
        menu = true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Equipa().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Equipa.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAnterior;
    private javax.swing.JButton BotaoProximo;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaAdmin;
    private javax.swing.JList<String> listaCozinha;
    private javax.swing.JList<String> listaMesa;
    private javax.swing.JList<String> listaNaoAtivo;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
