/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empregado_mesa;

import Adminstrador.*;
import Design.*;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import BD.*;
import Thread.MostrarInterface;
import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Adicionar ou remover personalizações dos produtos
 *
 * @author sofia
 */
public class Ver_mesa extends javax.swing.JFrame {

    
    DesignAdicionarCategoria design = new DesignAdicionarCategoria(this);
    ConfiguracaoEstabelecimento mesa = new ConfiguracaoEstabelecimento();
    short selecao = 0;
    Mesas Mesa = new Mesas();
    Pedidos Pedidos = new Pedidos();
    
    public Ver_mesa() throws ClassNotFoundException, SQLException {
        final int botao;
        
        initComponents();
        int x = 0;
        int y = 80;
        int num = 0;
        String[] mesas = Mesa.VerMesas().split("\n");
	int numeroConvertido;
	for (int i = 0 ; i < mesas.length; i++) {			
            numeroConvertido = Integer.parseInt(mesas[i]);  
            num= Mesa.id_pedido(numeroConvertido);
            Button b = new Button(mesas[i]);
            if (Pedidos.pedidos_ativos(num) == true) {
                b.setBackground(Color.RED);
            }
            b.setBounds(x, y, 75, 75);
            b.setActionCommand(mesas[i]);
            
            b.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // e.getActionCommand() vai retornar o nome do botao que vc clicou.
                    System.out.println("Button clicked: " + e.getActionCommand());
                    int botao = Integer.parseInt(e.getActionCommand());
                    pedir_pedido pedido;
                    try {
                        pedido = new pedir_pedido();
                        
                         pedido.setNumMesa(botao);
                    } catch (ClassNotFoundException | SQLException ex) {
                        Logger.getLogger(Ver_mesa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            
            MostrarInterface mi = new MostrarInterface(this, new pedir_pedido());
            
            add(b);
            if ((i+1) % 10 != 0){
                x= x + 90; 
            } else{
               x= 0;
               y= y + 80; 
            }
            
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        titulo.setText("Mesas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(titulo)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Ver_mesa().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ver_mesa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Ver_mesa.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
